#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
PolyCharge-Station login page. This page is used when a user wants to login or register to PolyCharge-station
"""

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

__author__ = 'Kevin Gauthier'
__copyright__ = 'Copyright 2020, PolyCharge'
__credits__ = ['PyQt5 UI code generator 5.15.0']
__version__ = '0.1.0'
__maintainer__ = 'Nikolay Radoev'
__email__ = 'nikolay.radoev@polymtl.ca'
__status__ = 'Done'


class Ui_Form(object):
    def __init__(self, widget, stationManager):
        self.widget = widget
        self.stationManager = stationManager
        self.setupUi(self.widget)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1073, 858)
        self.password_textEdit = QtWidgets.QLineEdit(Form)
        self.password_textEdit.setGeometry(QtCore.QRect(20, 302, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.password_textEdit.setFont(font)
        self.password_textEdit.setObjectName("password_textEdit")
        self.password_textEdit.setEchoMode(QLineEdit.Password)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 440, 1061, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.date_textEdit = QtWidgets.QLineEdit(Form)
        self.date_textEdit.setGeometry(QtCore.QRect(20, 652, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.date_textEdit.setFont(font)
        self.date_textEdit.setObjectName("date_textEdit")
        self.loginButton = QtWidgets.QPushButton(Form)
        self.loginButton.setEnabled(True)
        self.loginButton.setGeometry(QtCore.QRect(20, 360, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")
        self.loginButton_2 = QtWidgets.QPushButton(Form)
        self.loginButton_2.setEnabled(True)
        self.loginButton_2.setGeometry(QtCore.QRect(20, 710, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.loginButton_2.setFont(font)
        self.loginButton_2.setObjectName("loginButton_2")
        self.password_label = QtWidgets.QLabel(Form)
        self.password_label.setGeometry(QtCore.QRect(20, 260, 699, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.cvc_textEdit = QtWidgets.QLineEdit(Form)
        self.cvc_textEdit.setGeometry(QtCore.QRect(210, 650, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cvc_textEdit.setFont(font)
        self.cvc_textEdit.setObjectName("cvc_textEdit")
        self.credit_textEdit = QtWidgets.QLineEdit(Form)
        self.credit_textEdit.setGeometry(QtCore.QRect(20, 560, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.credit_textEdit.setFont(font)
        self.credit_textEdit.setObjectName("credit_textEdit")
        self.username_textEdit = QtWidgets.QLineEdit(Form)
        self.username_textEdit.setGeometry(QtCore.QRect(20, 201, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.username_textEdit.setFont(font)
        self.username_textEdit.setObjectName("username_textEdit")
        self.username_label_2 = QtWidgets.QLabel(Form)
        self.username_label_2.setGeometry(QtCore.QRect(20, 530, 699, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.username_label_2.setFont(font)
        self.username_label_2.setObjectName("username_label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 80, 1061, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.password_label_2 = QtWidgets.QLabel(Form)
        self.password_label_2.setGeometry(QtCore.QRect(20, 610, 151, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.password_label_2.setFont(font)
        self.password_label_2.setObjectName("password_label_2")
        self.username_label = QtWidgets.QLabel(Form)
        self.username_label.setGeometry(QtCore.QRect(20, 170, 699, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.username_label.setFont(font)
        self.username_label.setObjectName("username_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 1061, 83))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.password_label_3 = QtWidgets.QLabel(Form)
        self.password_label_3.setGeometry(QtCore.QRect(210, 610, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.password_label_3.setFont(font)
        self.password_label_3.setObjectName("password_label_3")
        self.password_textEdit_4 = QtWidgets.QLineEdit(Form)
        self.password_textEdit_4.setGeometry(QtCore.QRect(590, 302, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.password_textEdit_4.setFont(font)
        self.password_textEdit_4.setObjectName("password_textEdit_4")
        self.password_textEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_label_4 = QtWidgets.QLabel(Form)
        self.password_label_4.setGeometry(QtCore.QRect(590, 260, 699, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.password_label_4.setFont(font)
        self.password_label_4.setObjectName("password_label_4")
        self.username_label_3 = QtWidgets.QLabel(Form)
        self.username_label_3.setGeometry(QtCore.QRect(590, 170, 699, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.username_label_3.setFont(font)
        self.username_label_3.setObjectName("username_label_3")
        self.username_textEdit_2 = QtWidgets.QLineEdit(Form)
        self.username_textEdit_2.setGeometry(QtCore.QRect(590, 201, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.username_textEdit_2.setFont(font)
        self.username_textEdit_2.setObjectName("username_textEdit_2")
        self.loginButton_3 = QtWidgets.QPushButton(Form)
        self.loginButton_3.setEnabled(True)
        self.loginButton_3.setGeometry(QtCore.QRect(590, 360, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.loginButton_3.setFont(font)
        self.loginButton_3.setObjectName("loginButton_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)

        self.retranslateUi(Form)
        self.add_action_events()
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Login with credit card"))
        self.loginButton.setText(_translate("Form", "Login"))
        self.loginButton_2.setText(_translate("Form", "Login"))
        self.password_label.setText(_translate("Form", "Password"))
        self.username_label_2.setText(_translate("Form", "Credit Card Number"))
        self.label.setText(_translate("Form", "Login with username"))
        self.password_label_2.setText(_translate("Form", "Expiration Date"))
        self.username_label.setText(_translate("Form", "Username"))
        self.title_label.setText(_translate("Form", "Welcome to PolyCharge-Station!"))
        self.password_label_3.setText(_translate("Form", "CVC"))
        self.password_label_4.setText(_translate("Form", "Password"))
        self.username_label_3.setText(_translate("Form", "Username"))
        self.label_3.setText(_translate("Form", "Register"))
        self.loginButton_3.setText(_translate("Form", "Register"))

    def add_action_events(self):
        self.loginButton.clicked.connect(self.on_click_username)
        self.loginButton_2.clicked.connect(self.on_click_credit_card)
        self.loginButton_3.clicked.connect(self.on_click_register)

    def on_click_username(self):
        is_valid_credentials = self.stationManager.login_username(self.username_textEdit.text(), self.password_textEdit.text())

        if not is_valid_credentials:
            QMessageBox.question(self.widget, 'Message - PolyCharge-Station', "Error: Invalid Credentials", QMessageBox.Ok, QMessageBox.Ok)
            self.username_textEdit.setText("")
            self.password_textEdit.setText("")

    def on_click_register(self):
        if self.stationManager.register(self.username_textEdit_2.text(), self.password_textEdit_4.text()):
            QMessageBox.question(self.widget, 'Message - PolyCharge-Station', "User: " + self.username_textEdit_2.text() + " registered", QMessageBox.Ok, QMessageBox.Ok)
            self.stationManager.login_username(self.username_textEdit_2.text(), self.password_textEdit_4.text())
        else:
            QMessageBox.question(self.widget, 'Message - PolyCharge-Station', "Error: User: " + self.username_textEdit.text() + " already exist", QMessageBox.Ok,
                                 QMessageBox.Ok)

    def on_click_credit_card(self):
        is_valid_credentials = self.stationManager.login_credit(self.credit_textEdit.text(), self.date_textEdit.text(), self.cvc_textEdit.text())

        if not is_valid_credentials:
            QMessageBox.question(self.widget, 'Message - PolyCharge-Station', "Error: Invalid Credentials", QMessageBox.Ok, QMessageBox.Ok)
            self.credit_textEdit.setText("")
            self.date_textEdit.setText("")
            self.cvc_textEdit.setText("")

